font_family      JetBrains Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.2

window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0

#background_image none
#background_image_layout cscaled
#background_image_linear yes
dynamic_background_opacity yes
background_tint 0.9
background_opacity 0.2

window_logo_path ~/Downloads/pfpslol/hina.jpg
window_logo_alpha 0.9
window_logo_position bottom-right
window_logo_scale 8

# --- Cursor & Mouse ---
cursor_shape          beam
cursor_beam_thickness 1.8
cursor_blink_interval 0
detect_urls           yes
url_color             #bb9af7
url_style             curly

enable_audio_bell no

foreground            #ffffff
background #101216
selection_foreground  #1a1b26
selection_background  #f9a8d4
color0  #1a1b26
color8  #414868
color1  #f9a8d4
color9  #f9a8d4
color2  #b2fba5
color10 #b2fba5
color3  #ffccac
color11 #ffccac
color4  #7aa2f7
color12 #7aa2f7
color5  #bb9af7
color13 #bb9af7
color6  #7dcfff
color14 #7dcfff
color7  #c0caf5
color15 #ffffff

confirm_os_window_close -1
