# ~/.config/yazi/theme.toml

[manager]
border_symbol = "│"
border_style  = { fg = "#a6e3e9" } # Lavender borders

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#313244", bg = "#313244" }

[selection]
style = { fg = "#101216", bg = "#c5a880", bold = true } # Selection Tag

[hover]
style = { bg = "#a6e3e9", fg = "#101216" } # Hover Tag

# Controls the color of the filename text strings
[filetype]
rules = [
    { mime = "image/*", fg = "#a6e3e9" }, # Text Image Tag
    { mime = "video/*", fg = "#c5a880" }, # Text Video Tag
    { mime = "audio/*", fg = "#4b6584" }, # Text Audio Tag
    { url = "*.zip",    fg = "#c5a880" }, # Text Zip Tag
]
