background {
    path = /home/hinarch/Pictures/wallpapers/hdjingliu.png # Lock Wallpaper
    blur_passes = 2
    blur_size = 7
    noise = 0.0117
    contrast = 1.2
    brightness = 0.6
    vibrancy = 0.25
    vibrancy_darkness = 0.1
}

label { # DATE LABEL
    text = cmd[update:43200000] echo "$(date +"%A, %d %B")"
    color = rgb(c5a880) # Date Color
    font_size = 24
    font_family = JetBrainsMono Nerd Font Propo
    position = 0%, 45%
    shadow_passes = 1
    shadow_size = 3
    shadow_color = rgba(0, 0, 0, 0.2)
}

label { # TIME LABEL (HOUR)
    text = cmd[update:1000] echo "$(date +"%H")"
    color = rgb(a6e3e9) # Time Color
    font_size = 300
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = -5%, 35%
    shadow_passes = 4
    shadow_size = 12
    shadow_color = rgba(a6e3e966) # Time Glow
}

label { # TIME LABEL (MINUTE)
    text = cmd[update:1000] echo "$(date +"%M")"
    color = rgb(c5a880) # Minutes Color
    font_size = 300
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 5%, 25.0%
    shadow_passes = 4
    shadow_size = 12
    shadow_color = rgba(c5a88066) # Minutes Glow
}

label { # HELLO TEXT
    text = Hey $USER
    color = rgba(255, 255, 255, 0.6)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0%, 15%
    halign = center
    valign = center
}

image { # REAL PFP
    path = ~/Downloads/pfpslol/hina2.jpg
    size = 300
    rounding = -1
    border_size = 3
    border_color = rgb(a6e3e9) # PFP Border
    position = 0%, 0%
}

input-field {
    size = 420, 69
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.35
    dots_center = true
    dots_rounding = -1
    
    outer_color = rgb(c5a880) # Input Border
    inner_color = rgba(10121666) # Input Inner
    font_color = rgb(a6e3e9) # Input Font
    fade_on_empty = false
    placeholder_text = <3
    rounding = 16
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = rgb(234, 143, 255)

    position = 0%, -13.33%
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.3)
}
