# Display Settings
monitor = eDP-1, 2880x1800@1, 0x0, 1
monitor = HDMI-A-1, 2560x1440@120, auto, 1

# Startup Apps
exec-once = waybar & hyprpaper
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent

# Environment Variables
env = HYPRCURSOR_SIZE,24

general {
    gaps_out = 4
    gaps_in = 4
    border_size = 6
    
    col.active_border = rgb(f9a8d4) rgb(ffffff) 45deg
    col.inactive_border = rgba(1a1b26aa)

    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 8
    
    shadow {
        enabled = true
        range = 8
        render_power = 2
        color = rgba(1a1a1a66)
    }

    blur {
        enabled = true
        size = 6
        passes = 3
	    new_optimizations = true
    	xray = true
        noise = 0.05
        contrast = 0.9
        brightness = 0.8
        vibrancy = 0.2
    } 
}

animations {
    enabled = true
    bezier = a, 0.05, 0.9, 0.1, 1.1
    animation = workspaces, 1, 5, a, slidefade 42%
    animation = windows, 1, 5, a, popin 80%
    animation = windowsMove, 1, 5, a
    animation = windowsOut, 1, 5, a, popin 80%
    animation = fade, 1, 7, default
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_status = master
}
input { #Input settings
    kb_layout = us
    #Mouse
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = true
    }
}
#Hotkeys
bind = SUPER, RETURN, exec, kitty
bind = SUPER, Q, killactive
bind = SUPER, M, exit # log out
bind = SUPER, L, exec, hyprlock
bind = SUPER CONTROL, RETURN, exec, rofi -show drun -theme ~/.config/rofi/pastel.rasi
bind = SUPER, B, exec, brave
bind = SUPER, S, exec, hyprshot -m output --clipboard-only -m region

bind = SUPER, Tab, workspace, e+1 #windows tab
bind = SUPER SHIFT, Tab, workspace, e-1 #windows shift tab

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ #audio up
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- #audio down
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle #audio mute
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle #mic mute
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 5%+ #brightness up5
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 5%- #brightness down
bindl = CONTROL SUPER, bracketright, exec, playerctl next #next song
bindl = CONTROL SUPER, P, exec, playerctl play-pause #play pause
bindl = CONTROL SUPER, bracketleft, exec, playerctl previous #previous song
# Switch workspaces with mainMod + [0-9]
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5

bindl = , switch:Lid Switch, exec, hyprlock #closing lid locks out and uses hyprlock

bindm = SUPER, mouse:272, movewindow         # Move window position
bindm = SUPER, mouse:273, resizewindow       # resize window
bind = SUPER SHIFT, right, resizeactive, 100 0 # Increase window width with keyboard
bind = SUPER SHIFT, left, resizeactive, -100 0 # Reduce window width with keyboard
bind = SUPER SHIFT, down, resizeactive, 0 100  # Increase window height with keyboard
bind = SUPER SHIFT, up, resizeactive, 0 -100   # Reduce window height with keyboard
bind = SUPER, left, movefocus, l    #change active window left
bind = SUPER, right, movefocus, r   #change active window right
bind = SUPER, up, movefocus, u      #change active window up
bind = SUPER, down, movefocus, d    #change active window down

bind = SUPER, t, togglefloating #set active window floating
