background { #bg
    path = ~/Pictures/wallpapers/persona/1381893.webp
    blur_passes = 3
    blur_size = 1
    brightness = 0.67
}
label { #date
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(255, 255, 255, 0.67)
  font_size = 42
  font_family = JetBrains Mono Extra
  position = 0, -300
  halign = center
  valign = top
}

label { #time
  monitor = 
  text = cmd[update:1000] echo "$(date +"%-I:%M")"
  color = rgba(255, 255, 255, 0.67)
  font_size = 169
  font_family = JetBrains Mono Extrabold
  position = 0, 400
  halign = center
  valign = center
}


image { #pfp
    monitor =
    path = ~/Downloads/pfpslol/hina2.jpg
    size = 169
    position = 0, 100
    halign = center
    valign = center
}

input-field { #psswrd input
    monitor =
    position = 0,-100
    size = 420, 69
    dots_size = 0.15
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    fade_on_empty = false
    check_color = rgb(207, 69, 69)
    #placeholder_text = <i><span foreground="##cdd6f4">give pswrd lul</span></i>
}
